---
version: "2.1"
services:
  openvpn-as:
    image: hk59775634/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - 943:943
      - 443:443
      - 1194:1194/udp
    volumes:
      - ./openvpn:/openvpn
    restart: unless-stopped
